"""empty message

Revision ID: 1f91055502f7
Revises: 49f472077583
Create Date: 2020-08-01 16:24:25.714693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f91055502f7'
down_revision = '49f472077583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_index('ix_fingerprints_hash', table_name='fingerprints')
    op.drop_constraint('uq_fingerprints', 'fingerprints', type_='unique')
    op.drop_constraint('fk_fingerprints_song_id', 'fingerprints', type_='foreignkey')
    op.create_foreign_key(None, 'fingerprints', 'songs', ['song_id'], ['song_id'])
    op.create_unique_constraint(None, 'songs', ['file_sha1'])
    op.create_unique_constraint(None, 'songs', ['song_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_constraint(None, 'fingerprints', type_='foreignkey')
    op.create_foreign_key('fk_fingerprints_song_id', 'fingerprints', 'songs', ['song_id'], ['song_id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_fingerprints', 'fingerprints', ['song_id', 'offset', 'hash'])
    op.create_index('ix_fingerprints_hash', 'fingerprints', ['hash'], unique=False)
    op.drop_table('playlist')
    # ### end Alembic commands ###
