"""empty message

Revision ID: 4d205ebdc619
Revises: 89032adec3a2
Create Date: 2020-07-29 21:00:29.452743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d205ebdc619'
down_revision = '89032adec3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'songs', ['song_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='unique')
    # ### end Alembic commands ###
