"""empty message

Revision ID: 89032adec3a2
Revises: b0d0515035e2
Create Date: 2020-07-29 20:57:09.875945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89032adec3a2'
down_revision = 'b0d0515035e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('song_id', sa.Integer(), nullable=False))
    op.drop_column('songs', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('songs', 'song_id')
    # ### end Alembic commands ###
